<a href="https://colab.research.google.com/github/VidishaPonnappa/MachineLearning/blob/main/Project_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Goals :
1. Create a 3x3 matrix
2. Change dimensions of array; convert array to list
3. Find square roots of numbers in list


#### Activity 1: Create a 3 X 3 Matrix

To create a 3x3 matrix with values ranging from 2 to 10.

**For Example**:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import `numpy` module.

  - **Step 2**: Use `arange()` function to create array of numbers from 2 to 10 and `reshape()` function to reshape your array into another array having 3 rows and 3 columns. Store this reshaped array in a variable `x`.

  - **Step 3**: Print variable `x` to get the output.



In [ ]:
# Write your code here
# Step 1: Import numpy module
import numpy as np
# Step 2: Declare a variable 'x' to store the result and use 'arange()' and 'reshape()' functions
x=np.arange(2,11)
x=x.reshape(3,3)
# Step 3: Print the variable 'x' to see the output
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


---

#### Activity 2: Change Dimension of an Array and Convert the NumPy Array into a List

Write a program to change the dimension of an array (say `my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]`) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.

**For Example:**
```
Original array is [1 2 3 4 5 6 7 8 9]
Dimension is (9,)
Change array shape to (3, 3) -> 3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The data type of the converted variable is
 list
```


In [ ]:
# Write your code here
# Import numpy module
import numpy
# Create a NumPy array containing a list of numbers
a=np.arange(1,10)
# Print the dimension of the array
print('The dimensions of the array is ',a.shape)
# Change the dimension of the array into a 3 X 3
x=x.reshape(3,3)
# Print the array
print('The array is:\n',x)
# Convert the NumPy array into a Python list
a=list(a)
# Use type() function to verify the conversion
type(a)

The dimensions of the array is  (9,)
The array is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


list

---

#### Activity 3: Find Square Root and Calculate the value of $c$

Write a program to perform following two tasks:
-  Print the square root of numbers in the list.
- Compute the value of $c$ in the equation $c=\sqrt(a^2 + b^2)$.

**For Example**:

```
list1 = [4, 16, 9, 1, 25]
[2   4    3   1    5 ]
If a=27
   b=39
The value of c =  47.43416490252569
```
**Hint:** Use `np.sqrt()` function.


In [ ]:
# Write your solution here
l=[1,4,9,16,25]
for i in l:
  print(f'The root of {i} is {i**(1/2)}.')
a=int(input('Enter num1: '))
b=int(input('Enter num2: '))
c=((a**2)+(b**2))**(1/2)
print(f'The value of c in the equation with {a} and {b} is {c}')

The root of 1 is 1.0.
The root of 4 is 2.0.
The root of 9 is 3.0.
The root of 16 is 4.0.
The root of 25 is 5.0.
Enter num1: 27
Enter num2: 39
The value of c in the equation with 27 and 39 is 47.43416490252569


---